"""update project id not null

Revision ID: 3c493736e444
Revises: 5f50ba51af54
Create Date: 2026-03-19 21:23:14.913426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c493736e444'
down_revision: Union[str, None] = '5f50ba51af54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
